openapi: 3.0.3
info:
  title: ConverterCalc API
  version: 1.0.0
  description: API for ConverterCalc calculations and plotting

paths:
  /root:
    get:
      summary: Welcome message
      description: Returns a welcome message for the ConverterCalc API
      responses:
        '200':
          description: Successful response
          content:
            application/json:    
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome to ConverterCalc API up and running..."

    post:
      summary: Generate response plot
      description: Generates a plot based on provided parameters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Params'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  img:
                    type: string
                    description: Base64 encoded plot image
                  transfer_func:
                    type: string
                    description: Transfer function of the system

components:
  schemas:
    Params:
      type: object
      properties:
        d:
          type: number
          format: float
        vin:
          type: number
          format: float
        inductor:
          type: number
          format: float
        capacitor:
          type: number
          format: float
        resistor:
          type: number
          format: float
        mode:
          type: string
      required:
        - d
        - vin
        - inductor
        - capacitor
        - resistor
        - mode

servers:
  - url: http://0.0.0.0:80
    description: Local development server